### ISSUE TITLE
Is Sandbox available for BitPay.

### ISSUE THREAD

**Issue by tejaprakash** [bitpay/csharp-bitpay-client#10]
Hi Ionux,

Is Sandbox available for BitPay?

**Comment by ionux** [comment]
Yes:  https://test.bitpay.com

**Comment by MsudhakarphpProgrammer** [comment]
how to send bitpay amount any sample demo

**Comment by MsudhakarphpProgrammer** [comment]
how to work for after https://test.bitpay.com/invoice?id=R6RdHmm8w93oaPmB9H6FuT
in bitpay account any demo pls give me
