### ISSUE TITLE
Removed dll dependency

### ISSUE THREAD

**Issue by ecoinio** [bitpay/csharp-bitpay-client#13]
Can we replace dll dependency by install appropriate nuget packages? there is an issue with BitcoinSharp - the version used in bitpay client is not available officially via nuget server. Also is it possible to remove BitcoinSharp dependency since it was updated last time in 2011

**Comment by FlYnN91** [comment]
I've noticed this too. Seems strange that this dependency is not documented anywhere. Unless you know that this client requires BitCoinSharp, you'll be chasing error messages.

**Comment by ajp8164** [comment]
We welcome a contribution to remove the BitcoinSharp dependency. This should also allow for an upgrade to BC 1.8. Please issue a PR.
