### ISSUE TITLE
about "Unauthorized sin"

### ISSUE THREAD

**Issue by thortony** [bitpay/csharp-bitpay-client#14]
I make a token and post to "https://bitpay.com/tokens"
I get a pairingCode,but when I use this pairingCode to post  to "https://bitpay.com/tokens" again,it Error: 500.how to fix it?

**Comment by thortony** [comment]
private bool tryGetAccessTokens()
        {
            // Attempt to get access tokens for this client identity.
            try
            {
                // Success if at least one access token was returned.
                return this.getAccessTokens() > 0;
            }
            catch (BitPayException ex)
            {
                // If the error states that the identity is invalid then this client has not been
                // registered with the BitPay account.
                if (ex.getMessage().Contains("Unauthorized sin"))
                {
                    this.clearAccessTokenCache();
                    return false;
                }
                else
                {
                    // Propagate all other errors.
                    throw ex;
                }
            }
        }
public int getAccessTokens()
        {
            this.clearAccessTokenCache();
            Dictionary<String, String> parameters = this.getParams();
            string response = this.get("api/token", parameters);
            _tokenCache = responseToTokenCache(response);
            return _tokenCache.Count;
        }
private Dictionary<string, string> getParams()
        {
            Dictionary<string, string> parameters = new Dictionary<string, string>();
            parameters.Add("nonce", NextNonce + "");
            return parameters;
        }

**Comment by dewildef** [comment]
Has someone got a solution for this issue ?

**Comment by kleetus** [comment]
Can you provide the POST request that generated the 500?

**Comment by dewildef** [comment]
**Request**
GET https://test.bitpay.com/tokens?nonce=635907140744629 HTTP/1.1
x-accept-version: 2.0.0
x-bitpay-plugin-info: BitPay CSharp Client 2.0.0
x-signature: 3046022100d7e97d86a0334ebe25577cd146de09023f40c566e2c05ea91ba5f771f3430e39022100ced16832c7b59cde5bd29779d6ec418c8a4b3d96ecd618ae20c765fe8e6953f4
x-identity: 04f09c43cff24e824a57bff5c794e2d714620648571fb17a6fe40376130b3121f7f6181c773ed318a38ce25b6a1b475c1e7c79ccdca5fb58dba9a859b3b76673cb
Host: test.bitpay.com
Connection: Keep-Alive
**Response**
HTTP/1.1 500 Internal Server Error
Server: cloudflare-nginx
Date: Wed, 10 Feb 2016 23:14:35 GMT
Content-Type: application/json; charset=utf-8
Content-Length: 28
Connection: keep-alive
Set-Cookie: __cfduid=d5106148d8ada6c8316a9c2e47823b9391455146075; expires=Thu, 09-Feb-17 23:14:35 GMT; path=/; domain=.bitpay.com; HttpOnly
Strict-Transport-Security: max-age=31536000
X-Download-Options: noopen
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: HEAD,GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Headers: Content-Type,Authorization,Content-Length,X-Requested-With,Cache-Control,X-Accept-Version,x-signature,x-pubkey,x-identity,cf-connecting-ip
x-deprecated-in-favor-of: none
ETag: W/"1c-8de52758"
set-cookie: connect.sid=s%3AVZqx6prDdnup8DEoSdelSJRxvgPPsYmb.tly916lNlkzT8w7PfLjkoZ%2BsCJyv3U6OsR7T%2BSSsl7o; Path=/; HttpOnly; Secure
CF-RAY: 272b82db8af4115f-DFW

{"error":"Unauthorized sin"}

**Comment by kleetus** [comment]
Thanks for providing this. The request you provided is a GET request with a nonce as a query param. This does not look correct. If this came from the library, can you provide some sample code of the way you used it? Also, this might be a good tool to test with:

http://harness.b-pay.net/

**Comment by dewildef** [comment]
I downloaded the solution from github and just executed the following Test 2 code:(It broke every time at the bitpay = new BitPay(clientName); 
private BitPay bitpay;
        private static String clientName = "BitPay C# Library Tester on " + System.Environment.MachineName;

        public BitPayTest2()
        {
            try
            {
		        // If this test has never been run before then this test must be run twice in order to pass.
		        // The first time this test runs it will create an identity and emit a client pairing code.
		        // The pairing code must then be authorized in a BitPay account.  Running the test a second
		        // time should result in the authorized client (this test) running to completion.
                bitpay = new BitPay(clientName);        
        
                if (!bitpay.clientIsAuthorized(BitPay.FACADE_MERCHANT))
                {
                    // Get POS facade authorization code.
                    // Obtain a pairingCode from the BitPay server.  The pairingCode must be emitted from
        	        // this device and input into and approved by the desired merchant account.  To
        	        // generate invoices a POS facade is required.
                    String pairingCode = bitpay.requestClientAuthorization(BitPay.FACADE_MERCHANT);

                    // Signal the device operator that this client needs to be paired with a merchant account.
                    System.Diagnostics.Debug.WriteLine("Info: Pair this client with your merchant account using the pairing code: " + pairingCode);
                    throw new BitPayException("Error: client is not yet authorized, pair this client with your BitPay merchant account using the pairing code: " + pairingCode);
                }
            }
            catch (Exception ex)
            {
                Assert.Fail(ex.Message);
            }

**Comment by dewildef** [comment]
Do I need to hardcode a key somewhere on my client solution.  How does it know how to connect to the my account ?

**Comment by cataquil** [comment]
I expect bitpay have so many keys installed on their devboxes they have no
clue what using there own api is like

**Comment by kleetus** [comment]
closed by #17
