### ISSUE TITLE
The type 'EcKey' is defined in an assembly that is not referenced. You must add a reference to assembly 'BitCoinSharp, Version=0.2.199.60, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by danielcamargo** [bitpay/csharp-bitpay-client#19]
Even when the dependency is satisfied, another issue comes up:

{"Could not load file or assembly 
'BouncyCastle.Crypto, Version=1.7.4114.6375, Culture=neutral, PublicKeyToken=0e99375e54769942' 
or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. 
(Exception from HRESULT: 0x80131040)":"BouncyCastle.Crypto, Version=1.7.4114.6375, Culture=neutral, PublicKeyToken=0e99375e54769942"}

**Comment by FlYnN91** [comment]
+1 I am seeing this bug too.

**Comment by FlYnN91** [comment]
In VisualStudio try to add nuget package BitCoinSharp: Install-Package BitCoinSharp

**Comment by ajp8164** [comment]
See #20
