### ISSUE TITLE
Send bitcoins through API

### ISSUE THREAD

**Issue by alirezanoori1986** [bitpay/csharp-bitpay-client#21]
Is it possible to **send** bitcoins to any address using API?

I want to integrate BitPay to my Asp.Net MVC website and want to let users receive bitcoins, send bitcoins, check their balance, etc.

From reading the intro, I couldn't find any way to send bitcoins to others. Is there a way? Does the API (even the original API) support this?

**Comment by ajp8164** [comment]
This API does not provide bitcoin transaction services.  You can look at bitcore.io for an API that provides these services.  This API is a C# wrapper for the bitpay merchant services API. Please see bitpay.com/api for documentation for this API.
