### ISSUE TITLE
Error : Unauthorized sin

### ISSUE THREAD

**Issue by stackmanoj** [bitpay/csharp-bitpay-client#22]
Hello I am implementing bitpay api using c# sdk
I am doing this according to 
http://help.bitpay.com/businesses-and-organizations/implementation-and-development/how-do-i-configure-and-use-the-bitpay-c-client-library
but unfortunately I am not achieving this.
I stuck at
`BitPay bitpay = new BitPay();`
every time .
I also tried
`ECKey key = KeyUtils.createEcKey();`
`this.bitpay = new BitPay(key);`
but key generates successfully but again I stuck at
`this.bitpay = new BitPay(key);`
Every time I am getting this message from bitpay server.
`{"error":"Unauthorized sin"}`
Any one have idea about it?

And I am not seeing my public key on dashboard. Any one know why public key is not showing.

Thanks

**Comment by ajp8164** [comment]
Have you been able to get the tests running successfully?  I recommend doing that as your starting point.  The key pair is actually created by the library (by default) and stored in a file on the local file system.  You will never see your public key on the BitPay dashboard; you will only see your client identity (sin == system identification number).  The sin is a derivation of the public key generated on your client.

**Comment by alfredrumss** [comment]
@stackmanoj  did you solve this?

**Comment by cizu64** [comment]
Please how do i get the SIN key? I have checked this article [(https://support.bitpay.com/hc/en-us/articles/115003001183-How-do-I-pair-my-client-and-create-a-token-](https://support.bitpay.com/hc/en-us/articles/115003001183-How-do-I-pair-my-client-and-create-a-token-) and they did not mention how to get a SIN

**Comment by smakosh** [comment]
> Please how do i get the SIN key? I have checked this article [(https://support.bitpay.com/hc/en-us/articles/115003001183-How-do-I-pair-my-client-and-create-a-token-](https://support.bitpay.com/hc/en-us/articles/115003001183-How-do-I-pair-my-client-and-create-a-token-) and they did not mention how to get a SIN

You can get it by using `bitauth`, `bitauth.generateSin().sin`
