### ISSUE TITLE
Nuget Update ??

### ISSUE THREAD

**Issue by UrizielTSD** [bitpay/csharp-bitpay-client#26]
Will the Nuget package be updated ?
We are working on a Bitcoin application right now, but the nuget library was update the last time 2 years ago, while this repository was updated recently ?

**Comment by pieterpoorthuis** [comment]
@MrTarantula I'm testing a configuration in an environment where we're also using BouncyCastle v 1.8.1. When I change the reference to v1.8.1 in BitPay.csproj, it will not work as it gives me an error:

 The type 'BigInteger' is defined in an assembly that is not referenced. You must add a reference to assembly 'BouncyCastle.Crypto, Version=1.7.4137.9283, Culture=neutral, PublicKeyToken=a4292a325f69b123'.

It looks like the error is from BitCoinSharp which requires version 1.7.4137

Any idea how to fix this?

**Comment by MrTarantula** [comment]
That is why I left BouncyCastle at the the older version in my PR. BitcoinSharp has not been maintained for several years and will not work with BouncyCastle > 1.7. BitcoinSharp would need to be updated and published to Nuget. 

If you don't want to rely on the (possibly gone) maintainers of BitcoinSharp, you could fork, update, and publish your own version of BitcoinSharp. Another option is to forget BitcoinSharp and use BouncyCastle directly (or another library) for your crypto. There's really no reason to use BitcoinSharp here, as all you are using it for is signing requests, which could be done with any crypto library.

**Comment by MrTarantula** [comment]
@pieterpoorthuis FYI there is a great reimplementation of your client [here](https://github.com/MetacoSA/NBitpayClient). It uses NBitcoin, which is the de facto standarad BTC C# library. I hope that helps.

**Comment by anbugal** [comment]
The Nuget packages are updated and available
