### ISSUE TITLE
Refunds?

### ISSUE THREAD

**Issue by aharonTrujillo** [bitpay/csharp-bitpay-client#29]
Hi guys
I'm implementing BitPay API working with the DLL you guys shared and everything's going pretty good, (invoices, rates, ledgers, etc), but now my client wants to deploy refunds in our implementation so, I started to look into the DLL and I didn't find anything in the code related to invoice refunds.

Does DLL support BitPay Invoice refunds? probably I'm missing something, newbie in the Blockchain world...

**Comment by aharonTrujillo** [comment]
Thanks for your reply @MrTarantula 

I did the same, I tried to add the refund functionality into the DLL but for some reason every refund request BitPay API is rejecting it with an Error status 401 'Unauthorized' response.
I'm using the same security token that I've been using to create invoices (that operation works totally fine, facade = 'merchant').

**Comment by MrTarantula** [comment]
It doesn't tell you this in the API documentation, but you may need to pass the invoice's token as a parameter, like I do [here](https://github.com/bitpay/csharp-bitpay-client/pull/28/files#diff-d66b65e220130cabb19532b0b5fac8ffR389) for settlements.

**Comment by MrTarantula** [comment]
Yes, I'm certain you need the invoice token, as shown [here](https://github.com/bitpay/java-bitpay-client/blob/0aac5e3fb1b51b402746998f8787dc8c84d2f343/src/controller/BitPay.java#L466) and [here](https://github.com/bitpay/ruby-client/blob/986ab1e3d63c9217170a76c829bb3dfa05f11f28/lib/bitpay/client.rb#L109).

**Comment by aharonTrujillo** [comment]
Hi @MrTarantula 
Sorry for the late response but I was trying to make things work and just to confirm with you that your were right I was adding the wrong token. 

I just updated the refund methods to adding the new 'token' parameter into the URL and changing the source for refund.token attribute.

Thanks for your help!!!

**Comment by MrTarantula** [comment]
That's great! Though it would be better if we didn't have to add basic functionality to something we already pay for.
