### ISSUE TITLE
BCH update?

### ISSUE THREAD

**Issue by sonny-chen** [bitpay/csharp-bitpay-client#30]
At this point new fields to support the upcoming BCH acceptance, such as transactionCurrency aren't implemented yet.

Will the client be updated soon?

**Comment by MrTarantula** [comment]
I also need to support BCH soon, so I added the fields. You can find the changes under the [BCH branch of my fork](https://github.com/MrTarantula/csharp-bitpay-client/tree/BCH). I haven't had a change to test it, and I also don't trust the developer documentation so right now all the new complex object fields are "stringy" (for example `Dictionary<string, string>`. `Dictionary<string, KeyValuePair<string, string>>`) and you'll have to parse to your type (decimal, double).

**Comment by sonny-chen** [comment]
Actually I did something similar while waiting for an official answer of this. But instead of Dictionary<string, string> I used Dictionary<string, decimal> for some of the new fields -- risky! I'll update mine to your version now.

Thanks for this!

**Comment by MrTarantula** [comment]
It's not risky to do it your way. The only reason I'm doing it is because there's a precedent for `Dictionary<string, string>` [here](https://github.com/bitpay/csharp-bitpay-client/blob/d7f26b64106c6d6a7797dee9db7ce43b90f319e9/BitPay/Invoice.cs#L180). And even in the [BitPay documentation](https://bitpay.com/api#resource-Invoices) under `Invoices.exchangeRates` the examples sometimes do and don't wrap currencies in quotes. IMO yours is the correct way to do it.

**Comment by Kukks** [comment]
Just use the unofficial implementation of this api @ https://github.com/MetacoSA/NBitpayClient
I just updated it to make sure it has the latest properties. It's also way cleaner in structure and utilizes NBitcoin. :)

**Comment by MrTarantula** [comment]
Yes. I started reimplementing this API myself when I got frustrated with how bad setup is for each project. My goal was to make it async, use maintained crypto libraries, and improve the structure. Then I found your library which has done all of that better than I can.

**Comment by Kukks** [comment]
Oh it's not mine; and it's part of a much bigger project: 
https://github.com/btcpayserver/btcpayserver

**Comment by anbugal** [comment]
The SDK is fully updated and aligned with the BitPay API
