### ISSUE TITLE
API Update

### ISSUE THREAD

**Issue by MrTarantula** [bitpay/csharp-bitpay-client#31]
https://support.bitpay.com/hc/en-us/articles/360000502006-Overview-of-Upcoming-BitPay-API-Changes-May-7-2018-

**Comment by MrTarantula** [comment]
Not mentioned in this article is a change to Settlements: `InvoiceData.PayoutPercentage` is now an object, not just a decimal:

```json
"payoutPercentage": { "USD": 100 }
```

It would have been nice to know of this change before my app broke.

**Comment by anbugal** [comment]
The SDK is fully updated and aligned with the BitPay API
