### ISSUE TITLE
Fix dependency on old version of BouncyCastle

### ISSUE THREAD

**Issue by pieterpoorthuis** [bitpay/csharp-bitpay-client#32]
Latest version of BouncyCastle is 1.8.3.
This current library depends on v1.7.4, which is years old.

This automatically removes the dependency on BitcoinSharp (referenced by older versions of BouncyCastle), as BitcoinSharp is no longer maintained.

BitcoinSharp is used for is signing requests, which could be done with any crypto library.

**Comment by anbugal** [comment]
Thanks for your report.
This issue is been fixed in the new version v2.0.1904
