### ISSUE TITLE
Newtonsoft.Json dependency load failed

### ISSUE THREAD

**Issue by XardasLord** [bitpay/csharp-bitpay-client#56]
I have an error on the very start of using BitPay.Net Setup utility

**An error occurred while loading the configuration.
 Error Details: Nie można załadować pliku lub zestawu 'Newtonsoft.Json, Version=
12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' lub jednej z jego za
leżności. Zlokalizowana definicja manifestu zestawu nie odpowiada odwołaniu do z
estawu. (Wyjątek od HRESULT: 0x80131040)**

**Comment by anbugal** [comment]
HI Paweł,

Thanks for your feedback. A new version of the Setup Utility is now available in this repo.

https://github.com/bitpay/csharp-bitpay-client/blob/master/Assemblies/BitPay.Net%20Setup%20utility.zip
