### ISSUE TITLE
Can't complete pairing code step via setup

### ISSUE THREAD

**Issue by intoccabil** [bitpay/csharp-bitpay-client#60]
What is the correct procedure? Shouldn't you be reading the error message from the InnerException?

![image](https://user-images.githubusercontent.com/2297986/65046092-9f109100-d968-11e9-9ab9-63f49d6380f7.png)

**Comment by anbugal** [comment]
Hi @intoccabil, you might be doing one of the following:
- Either you are pressing enter after selecting the desired option, if so, the application is checking testing the tokens straight away even before you approve them in your BitPay Dashboard.
-Or you have some internal limitations so the application is not connecting properly when running the tests.

Either way, if you are getting the Private Key and the Json file correctly generated with the tokens and you validated them in your dashboard, you are good to go.

**Comment by intoccabil** [comment]
Hello @anbugal.
No, I'm not pressing enter after selecting the desired option and there are no internal limitations. The problem lies in your exception check, please review the pull request #61 . 

But whatever, as you've correctly said, the config files are generated even without the check and it's possible to verify the pairing code on the website. When I use these files in my application, however, I get the "There is no token for the specified key" exception. That is my problem right now. Maybe I am reading the config files wrong somehow?

**Comment by anbugal** [comment]
Thanks for your contribution, regarding this error, it could be because of different reason so it always helps if you provide your code.

Either you are not adding the token for the expected Facade in the constructor/config file, or you are not defining what Facade you want to use on the specific method.

**Comment by intoccabil** [comment]
> or you are not defining what Facade you want to use on the specific method.

That's what I did wrong. Figured it out a bit earlier, the CreateInvoice method has "pos" facade defined as default optional parameter. Would be nice to find that in the docs, I stumbled upon this fact when I reviewed the bitpay source, haha. Thanks for your help, @anbugal !
