### ISSUE TITLE
Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0

### ISSUE THREAD

**Issue by sirikumara** [bitpay/csharp-bitpay-client#66]
Hi Team,

I tried to execute  BitPay.Net Setup but I got below error: 

>  An error occurred while loading the configuration.
 Error Details: Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Please direct me to fix this issue.

My ultimate target is to link the bitpay java sdk with my bitpay merchan account. So I am folowing below tutorial. Is that the vay to link the sdk and merchant account.

https://github.com/bitpay/java-bitpay-client/blob/master/GUIDE.md

Best regards
Sirkumara

**Comment by anbugal** [comment]
Hi @sirikumara,

Soon we will a new version of this BitPay.Net Setup utility.
As your intention is to integrate the Java SDK, you can use the alternative method which is the script [BitPaySetup.java](https://github.com/bitpay/java-bitpay-client/blob/master/src/setup/java/BitPaySetup.java) available in the Java SDK repository.

**Comment by sirikumara** [comment]
Thanks for the information. I could do it with BirPaySetup.java
