### ISSUE TITLE
BouncyCastle build for .net 3.5 instead of 4.0?

### ISSUE THREAD

**Issue by diyajunaid** [bitpay/csharp-bitpay-client#78]
Trying to build Portable.Licensing on .net framework 3.5 to integrate with another application which is on 3.5. But BouncyCastle.Crypto is causing this error: 

{System.BadImageFormatException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.7.4771.41295, Culture=neutral, PublicKeyToken=null' or one of its dependencies. This assembly is built by a runtime newer than the currently loaded runtime and cannot be loaded.
File name: 'BouncyCastle.Crypto, Version=1.7.4771.41295, Culture=neutral, PublicKeyToken=null'

the runtime version of BoucyCastle.Crypto is v4.0.30319

i need BouncyCastle.Crypto on .net framework 3.5. How can i achieve this?

**Comment by anbugal** [comment]
Hi @diyajunaid we can look into downgrading some dependencies to allow compatibility with .Net 3.5 SP1 but this would only be available in the next release which doesn't have a defined date yet so we suggest you upgrade your MS framework to 4.5.2 if not the latest. Meanwhile you could provide the version of BouncyCastle you are currently using.

**Comment by diyajunaid** [comment]
hi Antonio,
Thank you for your response.
I can't upgrade the app to any other version as it is a developed product
by some other company and it is not going to have any more updates it will
stay on 3.5 only.

I am using BouncyCastle.Crypto, Version=1.7.4771.41295.

Regards,
Diya

**Comment by anbugal** [comment]
In that case I suggest you reach out to integrations@bitpay.com providing the details of the issue mentioned above and the information about your merchant account so we can keep you posted about this issue.

**Comment by diyajunaid** [comment]
can you please elaborate about merchant account and bitpay. i am new to github. how do i get a merchant account.

**Comment by anbugal** [comment]
Hi @diyajunaid since the purpose if this issue is not to usage this SDK it does not present a real issue so I am closing it, please reach out so support@bitpay.com for further information about the service.
