### ISSUE TITLE
Token getting disabled while creating invoice through BITPAY

### ISSUE THREAD

**Issue by sandeep18051989** [bitpay/csharp-bitpay-client#79]
![image](https://user-images.githubusercontent.com/27719887/122469039-18279700-cfda-11eb-80f3-71d3579b7277.png)

**Comment by anbugal** [comment]
Please provide a clear description of this issue and steps to reproduce. Token can't be disabled by the SDK, it can only be disabled from the dashboard once approved.

**Comment by anbugal** [comment]
Closing as no clear description was provided
