### ISSUE TITLE
Bitpay Client ignores ApiUrl from config file and use  constant values always for both Test and Prod.

### ISSUE THREAD

**Issue by yuriysokha** [bitpay/csharp-bitpay-client#80]
Right now it does not matter if you specify ApiUrl in config file. Client will always use 
        public const string TestUrl = "https://test.bitpay.com/";
        public const string ProdUrl = "https://bitpay.com/";
        
In previous versions config values were supported. 

Changes was done in commit:

Revision: a85c0d1f9a291b3a5a89669d03f9bd3321902504
Date: 7/22/2019 4:42:44 PM
Message:
V3 architecture (#54)

How it was: _baseUrl = _configuration.GetSection("BitPayConfiguration:EnvConfig:"+ _env +":ApiUrl").Value;
How it is now: _baseUrl = _env == Env.Test ? Env.TestUrl : Env.ProdUrl;

**Comment by yuriysokha** [comment]
Yes.
BTC Pay server supports BitPay API. I'm using your library to integrate and create invoice on my own custom installation of BTC Pay Server. So URLs are different.

Bitpay Invoice API - BTCPay implements the same API as Bitpay for creating and managing invoices.
https://docs.btcpayserver.org/CustomIntegration/

This aproach was working before with a charm. I created a pull request to bring this ability back:
https://github.com/bitpay/csharp-bitpay-client/pull/81

Thank you for so quick response.

**Comment by anbugal** [comment]
@yuriysokha in that case you can go to https://bitpay.com/signup and create an account, that way you will be able to use this SDK.

I am closing this issue since it does not represent a real issue.
